name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run unit tests
      run: go test ./...
